"""Settings module for model reviews."""
MODELREVIEW_FORM_STATUS_FIELD_LABEL = "Status"
MODELREVIEW_FORM_REASON_FIELD_LABEL = "Reason"
MODELREVIEW_FORM_COMMENTS_FIELD_LABEL = "Comments"
MODELREVIEW_FORM_REVIEW_STATUS_VALIDATION_MSG = "Please submit an approval or rejection"
MODELREVIEW_FORM_REVIEW_MISSING_REASON = "Please provide a reason for your review"
