# Generated by Django 3.0.5 on 2020-09-18 18:41
# pylint: disable=invalid-name,missing-module-docstring,missing-class-docstring
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("model_reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reviewer", unique_together={("user", "review")},
        ),
    ]
