# Generated by Django 3.0.5 on 2020-05-30 17:07
# pylint: disable=invalid-name,missing-module-docstring,missing-class-docstring
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="TestModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Approved"),
                            ("3", "Pending"),
                            ("2", "Rejected"),
                        ],
                        db_index=True,
                        default="3",
                        max_length=1,
                        verbose_name="Review Status",
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Review Date"
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Review Reason"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "TestModel",
                "verbose_name_plural": "TestModels",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TestModel2",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Approved"),
                            ("3", "Pending"),
                            ("2", "Rejected"),
                        ],
                        db_index=True,
                        default="3",
                        max_length=1,
                        verbose_name="Review Status",
                    ),
                ),
                (
                    "review_date",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Review Date"
                    ),
                ),
                (
                    "review_reason",
                    models.TextField(
                        blank=True, default="", verbose_name="Review Reason"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
